aljabar matriks
.Tidak mengerjakan tidak boleh masuk
.berikan penjelasan apa itu matrix
.operasi matrix (penjumlahan ,perkalian, transpose matrix)
.membuat program untuk mengalikan matriks A dan B

In [7]:
import numpy as np
import sympy as sy

In [8]:
A = np.array ([[1,3,9],[3,-2,6],[9,4,1]])
print(A)

[[ 1  3  9]
 [ 3 -2  6]
 [ 9  4  1]]


In [9]:
B = np.array ([[1,7,5],[2,4,3]])
print(B)


[[1 7 5]
 [2 4 3]]


In [7]:
C = np.array ([[3,2],[-1,2],[3,5]])
print(C)

[[ 3  2]
 [-1  2]
 [ 3  5]]


In [6]:
D = np.array ([[5,3,4],[3,2,1],[1,4,9]])
print(D)

[[5 3 4]
 [3 2 1]
 [1 4 9]]


In [ ]:
A = np.array ([[1,3,9],[3,-2,6],[9,4,1]])
B = np.array ([[1,7,5],[2,4,3]])
C = np.array ([[3,2],[-1,2],[3,5]])
D = np.array ([[5,3,4],[3,2,1],[1,4,9]])
E = A+B
F = 2*A
G = A@c
H = B@C
// A(BC) + (AB)

g.shape untuk mengetahui matrix